version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStringSql=Server=database;TrustServerCertificate=True;Database=MovieManagementDB;User Id=sa; Password=Mudar123!@#
      - ConnectionStringRedis=redis:6379
    ports:
      - "5102:80" #Swagger
      - "9102:81" #Api
    depends_on:
      - database
      - redis
  
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Mudar123!@#
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  sqlserver_data: